module TrNgGrid.Constants {
    export var tableDirective = "trNgGrid";
    export var tableDirectiveAttribute = "data-tr-ng-grid";

    export var dataColumnIsAutoGeneratedAttribute = tableDirectiveAttribute + "-auto-generated";
    export var dataColumnIsAutoGeneratedField = tableDirective + "AutoGenerated";
    export var dataColumnIsCustomizedAttribute = tableDirectiveAttribute + "-customized";
    export var dataColumnIsCustomizedField = tableDirective + "Customized";

    export var sortFilter = tableDirective + "SortFilter";
    export var dataPagingFilter = tableDirective + "DataPagingFilter";
    export var translateFilter = tableDirective + "TranslateFilter";
    export var dataFormattingFilter = tableDirective + "DataFormatFilter";

    export var defaultTranslationLocale = "default";

    export var sectionDirective = tableDirective + "Section";
    export var sectionDirectiveAttribute = tableDirectiveAttribute + "-section";

    export var rowDirective = tableDirective + "Row";
    export var rowDirectiveAttribute = tableDirectiveAttribute + "-row";

    export var cellDirective = tableDirective + "Cell";
    export var cellDirectiveAttribute = tableDirectiveAttribute + "-cell";

    export var cellPlaceholderDirective = cellDirective + "Placeholder";
    export var cellPlaceholderDirectiveAttribute = cellDirectiveAttribute + "-placeholder";

    //var fieldNameAttribute = "field-name";
    //var isCustomizedAttribute = "is-customized";

    export var globalFilterDirective = tableDirective + "GlobalFilter";
    export var globalFilterDirectiveAttribute = tableDirectiveAttribute + "-global-filter";

    export var pagerDirective = tableDirective + "Pager";
    export var pagerDirectiveAttribute = tableDirectiveAttribute + "-pager";

    export var columnSortDirective = tableDirective + "ColumnSort";
    export var columnSortDirectiveAttribute = tableDirectiveAttribute + "-column-sort";

    export var columnFilterDirective = tableDirective + "ColumnFilter";
    export var columnFilterDirectiveAttribute = tableDirectiveAttribute + "-column-filter";

    export var gridConfigurationService = tableDirective + "Configuration";
    export var gridLoggingService = tableDirective + "Log";
    export var gridConfigurationProvider = gridConfigurationService + "Provider";
} 