module TrNgGrid {
    export enum GridSectionType {
        Enforced,
        Header,
        Body
    } 

    export interface IGridColumnOptions {
        displayName?: string;
        displayAlign?: string;
        displayFormat?: string;
        enableSorting?: boolean;
        enableFiltering?: boolean;
        cellWidth?: string;
        cellHeight?: string;
        filter?: string;
        colspan?: number;

        displayItemFieldName?: string;
        columnTitle?: string;
        fieldName?: string;
        isCustomized?: boolean;
        isAutoGenerated?: boolean;
        isNotLinkedToField?:boolean;
    }

    export class GridRow {
        cells: Array<IGridColumnOptions> =[];
        nonFieldNameTagIndex = 0;

        findCell(fieldName: string):IGridColumnOptions {
            for (var cellIndex = 0; cellIndex < this.cells.length; cellIndex++) {
                if (this.cells[cellIndex].fieldName === fieldName) {
                    return this.cells[cellIndex];
                }
            }

            return null;
        }

        registerCell(cell: IGridColumnOptions): IGridColumnOptions {
            if (!cell.fieldName) {
                cell.fieldName = "Custom_" + (this.nonFieldNameTagIndex++);
                cell.isNotLinkedToField = true;
            }

            var cellFound = false;
            for (var cellIndex = 0; (cellIndex < this.cells.length) && (!cellFound); cellIndex++) {
                if (this.cells[cellIndex].fieldName === cell.fieldName) {
                    if (cell.isAutoGenerated) {
                        cell = this.cells[cellIndex];
                    } else {
                        this.cells[cellIndex] = cell;
                    }
                    cellFound = true;
                }
            }

            if (!cellFound) {
                this.cells.push(cell);

                // the display field name is a safe property name for the displayed item
                cell.displayItemFieldName = cell.fieldName.replace(/[\.\[\]]/g, "_");

                // set up the column title and ensure the displayName attribute is being monitored for changes
                if (cell.displayName) {
                    cell.columnTitle = cell.displayName;
                } else if (!cell.isNotLinkedToField) {
                    // exclude nested notations and invalid letters
                    var rawTitle = cell.fieldName.replace(/^([^\a-zA-Z]*)([\a-zA-Z]*)(.*)/g, "$2"); // take just the first part

                    // split by camel-casing
                    var splitTitleName = rawTitle.split(/(?=[A-Z])/);
                    if (splitTitleName.length && splitTitleName[0].length) {
                        splitTitleName[0] = splitTitleName[0][0].toLocaleUpperCase() + splitTitleName[0].substr(1);
                    }
                    cell.columnTitle = splitTitleName.join(" ");
                } else {
                    cell.columnTitle = "";
                }
            }

            return cell;
        }

        unregisterCell(cell: IGridColumnOptions) {
            for (var cellIndex = 0; cellIndex < this.cells.length; cellIndex++) {
                if (this.cells[cellIndex] === cell) {
                    this.cells.splice(cellIndex, 1);
                    return;
                }
            }            
        }
    }

    /*
     * Holds details about a section (e.g. head, body, footer)
     * including the row composition.
     */
    export class GridSection {
        rows: Array<GridRow> = [];

        registerRow(): GridRow {
            var row = new GridRow();
            this.rows.push(row);
            return row;
        }

        unregisterRow(row: GridRow) {
            for (var rowIndex = 0; rowIndex < this.rows.length; rowIndex++) {
                if (this.rows[rowIndex] === row) {
                    this.rows.splice(rowIndex, 1);
                    return;
                }
            }
        }
    }

    /*
     * Holds details about the available sections in the grid.
     */
    export class GridLayout {
        private sections: Array<GridSection> = new Array(GridSectionType.Body + 1);

        getSection(section: GridSectionType):GridSection {
            var colSection = this.sections[section];
            if (!colSection) {
                this.sections[<number>section] = colSection = new GridSection();
            }

            return colSection;
        }
    }

} 