module TrNgGrid.Constants {
    export var tableDirective = "trNgGrid";
    export var tableDirectiveAttribute = "data-tr-ng-grid";

    export var dataColumnIsAutoGeneratedAttribute = tableDirectiveAttribute + "-auto-generated";
    export var dataColumnIsAutoGeneratedField = tableDirective + "AutoGenerated";
    export var dataColumnIsCustomizedAttribute = tableDirectiveAttribute + "-customized";
    export var dataColumnIsCustomizedField = tableDirective + "Customized";

    export var sortFilter = tableDirective + "SortFilter";
    export var dataPagingFilter = tableDirective + "DataPagingFilter";
    export var translateFilter = tableDirective + "TranslateFilter";
    export var dataFormattingFilter = tableDirective + "DataFormatFilter";

    export var defaultTranslationLocale = "default";

    export var bodyDirective = tableDirective + "Body";
    export var bodyDirectiveAttribute = tableDirectiveAttribute + "-body";

    export var bodyRowDirective = bodyDirective + "Row";
    export var bodyRowDirectiveAttribute = bodyDirectiveAttribute + "-row";

    export var headerDirective = tableDirective + "Header";
    export var headerDirectiveAttribute = tableDirectiveAttribute + "-header";

    export var headerRowDirective = headerDirective + "Row";
    export var headerRowDirectiveAttribute = headerDirectiveAttribute + "-row";

    export var footerDirective = tableDirective + "Footer";
    export var footerDirectiveAttribute = tableDirectiveAttribute + "-footer";

    //var fieldNameAttribute = "field-name";
    //var isCustomizedAttribute = "is-customized";

    export var cellFooterDirective = tableDirective + "FooterCell";
    export var cellFooterDirectiveAttribute = tableDirectiveAttribute + "-footer-cell";
    export var cellFooterTemplateDirective = tableDirective + "FooterCellTemplate";
    export var cellFooterTemplateDirectiveAttribute = tableDirectiveAttribute + "-footer-cell-template";

    export var globalFilterDirective = tableDirective + "GlobalFilter";
    export var globalFilterDirectiveAttribute = tableDirectiveAttribute + "-global-filter";

    export var pagerDirective = tableDirective + "Pager";
    export var pagerDirectiveAttribute = tableDirectiveAttribute + "-pager";

    export var cellHeaderDirective = tableDirective + "HeaderCell";
    export var cellHeaderDirectiveAttribute = tableDirectiveAttribute + "-header-cell";
    export var cellHeaderTemplateDirective = tableDirective + "HeaderCellTemplate";
    export var cellHeaderTemplateDirectiveAttribute = tableDirectiveAttribute + "-header-cell-template";

    export var cellBodyDirective = tableDirective + "BodyCell";
    export var cellBodyDirectiveAttribute = tableDirectiveAttribute + "-body-cell";
    export var cellBodyTemplateDirective = tableDirective + "BodyCellTemplate";
    export var cellBodyTemplateDirectiveAttribute = tableDirectiveAttribute + "-body-cell-template";

    export var columnSortDirective = tableDirective + "ColumnSort";
    export var columnSortDirectiveAttribute = tableDirectiveAttribute + "-column-sort";

    export var columnFilterDirective = tableDirective + "ColumnFilter";
    export var columnFilterDirectiveAttribute = tableDirectiveAttribute + "-column-filter";

    export var gridConfigurationService = tableDirective + "Configuration";
    export var gridConfigurationProvider = gridConfigurationService + "Provider";
} 